// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFymvfqdwiCeHb_sbaXuvVImvKAKYkLCk',
    appId: '1:146519717733:web:15699cf81568fd41b9d38c',
    messagingSenderId: '146519717733',
    projectId: 'notecore-dhc',
    authDomain: 'notecore-dhc.firebaseapp.com',
    storageBucket: 'notecore-dhc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCULsPg5sMQ1oMxzsLhuNa-2yQdnch84xg',
    appId: '1:146519717733:android:6adad1a0cfa0cf4eb9d38c',
    messagingSenderId: '146519717733',
    projectId: 'notecore-dhc',
    storageBucket: 'notecore-dhc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDunBqN3qPWACQqrW4HvrJOhgbAIcqxK3I',
    appId: '1:146519717733:ios:b24d9fda72f4c4e9b9d38c',
    messagingSenderId: '146519717733',
    projectId: 'notecore-dhc',
    storageBucket: 'notecore-dhc.appspot.com',
    iosClientId:
        '146519717733-0lnqd76930414nk3631kab32fkskntge.apps.googleusercontent.com',
    iosBundleId: 'com.dhc.notecore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDunBqN3qPWACQqrW4HvrJOhgbAIcqxK3I',
    appId: '1:146519717733:ios:b24d9fda72f4c4e9b9d38c',
    messagingSenderId: '146519717733',
    projectId: 'notecore-dhc',
    storageBucket: 'notecore-dhc.appspot.com',
    iosClientId:
        '146519717733-0lnqd76930414nk3631kab32fkskntge.apps.googleusercontent.com',
    iosBundleId: 'com.dhc.notecore',
  );
}
